### ISSUE TITLE
MacOSX Certain Modules can't Export following a Java update

### ISSUE THREAD

**Issue by Sciss** [Sciss/FScape#11]
In GitLab by @wintercouplet on Jun 23, 2020, 01:17

(Hopefully I'm submitting this correctly, made an account on this site entirely because I want to get fscape working for myself)

**Software details**

![Screen_Shot_2020-06-22_at_7.13.04_PM](https://my-gitlab-bucket.s3.amazonaws.com/4187471/02687b94295ae7f4eac9b796da24b180.png)

![Screen_Shot_2020-06-22_at_7.13.38_PM](https://my-gitlab-bucket.s3.amazonaws.com/4187471/a8a5e631877b3672f2f2ca96e46547e0.png)

+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

Hiya. So, at some point in time a few months ago, I BELIEVE after a java update but I may be incorrect, suddenly certain modules could just no longer export files. It generates this in the logs;

> java.io.IOException: No such file or directory
> 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
> 	at java.base/java.io.File.createTempFile(File.java:2090)
> 	at de.sciss.io.IOUtil.createTempFile(IOUtil.java:286)
> 	at de.sciss.io.IOUtil.createTempFile(IOUtil.java:259)
> 	at de.sciss.fscape.gui.FourierDlg.process(FourierDlg.java:487)
> 	at de.sciss.fscape.session.ModulePanel.run(ModulePanel.java:1255)
> 	at java.base/java.lang.Thread.run(Thread.java:835)

Some modules are still able to export, HOWEVER, absolutely NO modules can export if the Normalized option for volume Gain is enabled, if I attempt to export from modules that usually work, I get seemingly identical errors;

> java.io.IOException: No such file or directory
> 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
> 	at java.base/java.io.File.createTempFile(File.java:2090)
> 	at de.sciss.io.IOUtil.createTempFile(IOUtil.java:286)
> 	at de.sciss.io.IOUtil.createTempFile(IOUtil.java:259)
> 	at de.sciss.fscape.gui.LaguerreDlg.process(LaguerreDlg.java:416)
> 	at de.sciss.fscape.session.ModulePanel.run(ModulePanel.java:1255)
> 	at java.base/java.lang.Thread.run(Thread.java:835)

For the ones that don't export at all, I'm not entirely sure if they ever would've worked at some point, as I hadn't tested all of them at that time. 

However, I am completely sure that there was a point which the modules that are still capable of exporting were not made unable when Normalized is selected.

+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

I'll supply a couple screenshots of errors I'm getting, just in case that would be of any help. I've spent quite a few hours attempting to fix this. You may notice the imported filenames and think that weird characters could potentially be contributing to the errors, but I've considered this and upon testing, this makes no difference.

![Screen_Shot_2020-06-22_at_7.01.40_PM](https://my-gitlab-bucket.s3.amazonaws.com/4187471/9a1f5a5466d6b95e24b329a17c918a81.png)

![Screen_Shot_2020-06-22_at_6.58.30_PM](https://my-gitlab-bucket.s3.amazonaws.com/4187471/2e0088b3d3030d78ccc3a0c36e5213cd.png)

I absolutely adore fscape and I'd really like to figure out how to fix these issues so I can get back to using it daily as I was before.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Jun 23, 2020, 09:49

Hallo Valyri, thanks for reporting. The error indicates that FScape cannot create temporary (background) files, which is also supported by the fact the problem occurs when normalising (in this case, we render first to a temporary file, then to the actual output).

My guess is that the location for temporary files became invalid with your OS update. Please open the FScape preferences and check the very first item  "Temporary Folder". This needs to point to a valid and existing directory. You can try and change it to any other directory. Let me know if this helps.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Jun 23, 2020, 09:51

In general, Java 12 is not recommended. Is there a reason you don't use the "full" macOS built from https://archive.org/download/FScape - it comes with Java 11 bundled, which is the recommended version. This doesn't interfere with any existing Java installation of your system.

**Comment by Sciss** [comment]
Attaching screenshots  that didn't get through GitLab > GH migration

![Screen_Shot_2020-06-22_at_6 58 30_PM](https://user-images.githubusercontent.com/131300/116071983-d3911680-a68e-11eb-8cb9-aaed8d4789e2.png)
![Screen_Shot_2020-06-22_at_7 13 04_PM](https://user-images.githubusercontent.com/131300/116071975-d12ebc80-a68e-11eb-8a70-149c15479708.png)
![Screen_Shot_2020-06-22_at_7 13 38_PM](https://user-images.githubusercontent.com/131300/116071978-d25fe980-a68e-11eb-8ec2-dd716515d45c.png)
![Screen_Shot_2020-06-22_at_7 01 40_PM](https://user-images.githubusercontent.com/131300/116071981-d2f88000-a68e-11eb-8358-2844f6bdbde3.png)

**Comment by Sciss** [comment]
replaced by #12
